### PR TITLE
Try a different variant of `post-if` syntax

### PR DESCRIPTION
**Pull request by mjgpy3**
What I had before doesn't seem to work.

I found this in some random repo and hope it works: https://github.com/dhadka/test-post-if-condition/blob/5f3262a08c5774e646fd9c883d3522d9e9fd6f15/action.yml

### CODE REVIEW

**Review by pbrisbin — COMMENTED** [review]
Can you update the example or integration test as necessary to exercise this, so we're not flying so blind?

I'll Approve anything, but only if we know it works :)

**Comment by mjgpy3** [comment]
Yeah it's not working :(

**Comment by mjgpy3** [comment]
This just isn't working...

**Comment by pbrisbin** [comment]
Seems like the only one that worked was `always()`,



Or `failure()`:



But that at least proves `post-if` does function.

And any time you tried to combine them with `inputs` you had trouble.

I **know** [this works](https://github.com/freckle/platform-deploy-action/blob/main/action.yml#L50).

So, did you happen to try?

```yaml
post-if: ${{ success() || input.always-store == 'true' }}
```

?

It looks like you tried it in the opposite order of expressions, which gave you



But I wonder about the other way.

**Comment by mjgpy3** [comment]
Same deal https://github.com/freckle/stack-cache-action/runs/5683044958?check_suite_focus=true

**Comment by pbrisbin** [comment]
What on earth. How is that other action working?

**Comment by pbrisbin** [comment]
I guess it is two totally different things. An `if:` in an actual workflow would for sure support interpolations, but it would make sense as a sort of "stage restriction" that you can't interpolate in an `action.yaml` (or if you do, `success()` indeed means nothing since nothing is execution when the action itself is loaded).

I think the string `post-if: "success() || inputs.always-store == 'true'"` is the only that would stand a chance of working, as that string would get passed down and executed later. But I can also see them having restrictions on what such a "we're going to eval this" string can hold.

**Pull request closed without merging**
